kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: nginxwebapp-hpa
spec:
  maxReplicas: 7
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginxwebapp-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
